### ISSUE TITLE
Cannot read property '_isDestroyed' of undefined

### ISSUE THREAD

**Issue by kamilic** [Zippowxk/vue-router-keep-alive-helper#23]
在 https://github.com/Zippowxk/vue-router-keep-alive-helper/blob/main/src/historyStack.js#L10 的栈中会发现有时会有空的 vm 实例，导致报错。

**Comment by Zippowxk** [comment]
K神能用codepen复现一下吗，这里可以加一个非空校验，按说没有理由为空

**Comment by kamilic** [comment]
@Zippowxk  我是在我们内部的监控系统看到的，按道理我也觉得不可能为空。。 😂
> K神能用codepen复现一下吗，这里可以加一个非空校验，按说没有理由为空

**Comment by Zippowxk** [comment]
为空时 我们也过滤掉，这个策略没问题吧

**Comment by kamilic** [comment]
@Zippowxk 不太确定，太久了有点忘了代码逻辑。

**Comment by kamilic** [comment]
@Zippowxk  
推测是这里，会返回 undefined.
https://github.com/Zippowxk/vue-router-keep-alive-helper/blob/649ebc06d64a8f566b31cbdda09e1b2206d853e1/src/utils.js#L9

然后这里也能直接 push，可能需要对 pendingToPushVm 做一下判断才确定推不推进去。
https://github.com/Zippowxk/vue-router-keep-alive-helper/blob/649ebc06d64a8f566b31cbdda09e1b2206d853e1/src/helper.js#L51

**Comment by Zippowxk** [comment]
所以此时也是用Place_holder 入栈， 你觉得可以解决这个问题吗。这样的修改 怎么测试呢？

**Comment by kamilic** [comment]
> 所以此时也是用Place_holder 入栈， 你觉得可以解决这个问题吗。这样的修改 怎么测试呢？

@Zippowxk 现在好像不是 placeholder 的问题，是有些时候这个 vm 是 undefined / null。

两种方法：
1.  丢弃这个 vm 
2. 把这个 vm 转为 placeholder

**Comment by kamilic** [comment]
我觉得过滤的时候加个非空校验就好了，因为在栈中是基于 key 来匹配的

**Comment by kamilic** [comment]
@Zippowxk 
你这个分支 build 一下？我这里直接用 npm 安装你的这条分支，我试试有没有问题再给你反馈

**Comment by Zippowxk** [comment]
好的 今天稍晚一点

**Comment by kamilic** [comment]
@Zippowxk 可以不？？

**Comment by Zippowxk** [comment]
已PUSH

**Comment by Zippowxk** [comment]
> @Zippowxk 可以不？？

可以安装吗？

**Comment by kamilic** [comment]
可以 要等待测试

**Comment by Zippowxk** [comment]
> 可以 要等待测试

静候佳音

**Comment by kamilic** [comment]
不行呢，改完之后变成必现的问题了。
我在同一个路由的页面更新几次（a -> a?id=1 -> a?id=2 -> a?id=3），然后回退就出现了同样的报错。 
@Zippowxk

**Comment by Zippowxk** [comment]
我在自己的项目中有同样的场景，但是并没有得到相似的报错。报错会导致返回失败吗？

**Comment by kamilic** [comment]
> 我在自己的项目中有同样的场景，但是并没有得到相似的报错。报错会导致返回失败吗？

@Zippowxk 你说这个新版本还是原来的版本？

**Comment by Zippowxk** [comment]
发布版，那我试一下 这个测试版

**Comment by Zippowxk** [comment]
> 不行呢，改完之后变成必现的问题了。
> 我在同一个路由的页面更新几次（a -> a?id=1 -> a?id=2 -> a?id=3），然后回退就出现了同样的报错。

尝试了一下，也没有复现出相同的问题，是`/a`没有keep-alive吗？

**Comment by kamilic** [comment]
我们测了也没有什么问题了，刚刚是没有安装正确的问题。
上线跑两天看看监控有没有报错再给你反馈。

**Comment by Zippowxk** [comment]
> 我们测了也没有什么问题了，刚刚是没有安装正确的问题。
> 上线跑两天看看监控有没有报错再给你反馈。

好的

**Comment by kamilic** [comment]
@Zippowxk 新问题
![image](https://user-images.githubusercontent.com/8327041/135033128-03d275e7-7b1c-4371-940d-545020c10ce6.png)

**Comment by Zippowxk** [comment]
> @Zippowxk 新问题
> ![image](https://user-images.githubusercontent.com/8327041/135033128-03d275e7-7b1c-4371-940d-545020c10ce6.png)

已增加安全校验，并打包，上传了最新的供测试

**Comment by kamilic** [comment]
@Zippowxk 
看了下代码，这样应该还是会报。
https://github.com/Zippowxk/vue-router-keep-alive-helper/commit/6af92a0492b0243553026259ee7e8e4a7a92e478#diff-85b18f65b01cea7762ab044d7df73c7d3e6de0c9e3502cce8540cad8f2534039R164

这样才行。
```javascript
this.pre?.$keepAliveDestroy?.();
```

**Comment by Zippowxk** [comment]
已push新的build

**Comment by kamilic** [comment]
![image](https://user-images.githubusercontent.com/8327041/136727905-5c64135e-7a30-4e41-9a95-5f10994514e4.png)
@Zippowxk 感觉得查查为什么为空 要不然全部都要做判空测试

**Comment by kamilic** [comment]
https://github.com/Zippowxk/vue-router-keep-alive-helper/blob/fix-issue-23/src/historyStack.js#L10

**Comment by Zippowxk** [comment]
![截屏2021-10-11 11 11 41](https://user-images.githubusercontent.com/5326755/136728172-e0a73fd7-3358-4c1b-8647-1e0c2e503bbe.png)
@kamilic 我用的sentry 追踪线上问题，但是没有报过类似的问题。你有手动调用过vue的destroy吗，
会不会是非keep-alive页面销毁导致的呢？

**Comment by kamilic** [comment]
@Zippowxk 我排查下

**Comment by kamilic** [comment]
@Zippowxk 这错误自然消灭了，突然就没了。。
