### ISSUE TITLE
A页面进到B页面后，点击退回到A页面，再进入B页面，B页面没有销毁

### ISSUE THREAD

**Issue by suzhenghui-sky** [Zippowxk/vue-router-keep-alive-helper#34]
A页面进到B页面后，点击退回到A页面，再进入B页面，B页面没有销毁。请问这是什么回事?

**Comment by Zippowxk** [comment]
请问可以提供一个复现代码吗？或者你可以拉取https://github.com/Zippowxk/vue-router-helper-demo这个代码参考一下

**Comment by suzhenghui-sky** [comment]
你好这个我的问题，不过我发现了另一个问题，我提新的issus
